"""Alter pipeline-item-type

Revision ID: 0016945d3433
Revises: e6dd4fbacead
Create Date: 2025-09-13 21:17:53.441430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016945d3433'
down_revision: Union[str, None] = 'e6dd4fbacead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    #op.execute("ALTER TYPE pipelineitemtype ADD VALUE 'CHATBOT_PREPARE'")
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###