"""Add pinned_at column to conversation 1

Revision ID: 00379b9b48a5
Revises: 3d7370ccf381
Create Date: 2025-11-15 19:30:19.121379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00379b9b48a5'
down_revision: Union[str, None] = '3d7370ccf381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_pinned')
    # ### end Alembic commands ###