"""Remove InitStatuts

Revision ID: 18404840ce3e
Revises: 4fa49aa94687
Create Date: 2025-09-01 13:14:07.530810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18404840ce3e'
down_revision: Union[str, None] = '4fa49aa94687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###