"""Alter Records add current_step

Revision ID: 233040537aac
Revises: a3911a75eb4b
Create Date: 2025-09-03 11:22:37.737936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233040537aac'
down_revision: Union[str, None] = 'a3911a75eb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('current_step', sa.Enum('CREATE_RECORD', 'TRANSCRIBE', 'RAG_INDEX', 'GENERATE_SUM', name='pipelineitemtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'current_step')
    # ### end Alembic commands ###