"""add AgentMsgStatus

Revision ID: 24b349658f6a
Revises: d455fc98bf63
Create Date: 2025-09-28 15:58:08.173810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b349658f6a'
down_revision: Union[str, None] = 'd455fc98bf63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    agent_msg_status = sa.Enum(
        'SUCCESS',
        'FAILED',
        name='agentmsgstatus'
    )
    agent_msg_status.create(op.get_bind())
    op.add_column('messages', sa.Column('agent_msg_status', sa.Enum('SUCCESS', 'FAILED', name='agentmsgstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'agent_msg_status')
    # ### end Alembic commands ###