"""Add record-summary-versions1

Revision ID: 2793fe269a66
Revises: 48f8743896e4
Create Date: 2025-09-07 11:22:15.431730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2793fe269a66'
down_revision: Union[str, None] = '48f8743896e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('records_current_version_id_fkey'), 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'summary_versions', ['current_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key(op.f('records_current_version_id_fkey'), 'records', 'summary_versions', ['current_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###