"""Fix relationship

Revision ID: 3a990a244f14
Revises: f05fe8b5db2e
Create Date: 2025-08-31 19:00:21.207373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a990a244f14'
down_revision: Union[str, None] = 'f05fe8b5db2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('records', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('records', 'description')
    # ### end Alembic commands ###