"""Add pinned_at column to conversation

Revision ID: 3d7370ccf381
Revises: 740ca21583d0
Create Date: 2025-11-15 19:16:44.965933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7370ccf381'
down_revision: Union[str, None] = '740ca21583d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pinned_at')
    # ### end Alembic commands ###