"""Add record-summary-versions

Revision ID: 48f8743896e4
Revises: a8bfe0ec5834
Create Date: 2025-09-07 09:26:42.268358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f8743896e4'
down_revision: Union[str, None] = 'a8bfe0ec5834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_versions',
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_versions_is_deleted'), 'summary_versions', ['is_deleted'], unique=False)
    op.drop_index(op.f('idx_rag_chunks_embedding_hnsw'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.add_column('records', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'records', 'summary_versions', ['current_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'current_version_id')
    op.create_index(op.f('idx_rag_chunks_embedding_hnsw'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_summary_versions_is_deleted'), table_name='summary_versions')
    op.drop_table('summary_versions')
    # ### end Alembic commands ###