"""Add PipelineItemsTable

Revision ID: 4fa49aa94687
Revises: 50f59d2bd795
Create Date: 2025-09-01 13:06:47.573160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa49aa94687'
down_revision: Union[str, None] = '50f59d2bd795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_pipeline_items',
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('CREATE_RECORD', 'TRANSCRIBE', 'RAG_INDEX', 'GENERATE_SUM', name='pipelineitemtype'), nullable=False),
    sa.Column('status', sa.Enum('INITIALIZED', 'PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='pipelineitemstatus'), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_pipeline_items_is_deleted'), 'record_pipeline_items', ['is_deleted'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_record_pipeline_items_is_deleted'), table_name='record_pipeline_items')
    op.drop_table('record_pipeline_items')
    # ### end Alembic commands ###