"""alter Record add thumbnail

Revision ID: 740ca21583d0
Revises: 24b349658f6a
Create Date: 2025-10-08 21:18:29.983944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740ca21583d0'
down_revision: Union[str, None] = '24b349658f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'thumbnail')
    # ### end Alembic commands ###