"""Alter pipeline-item-type CHATBOT_PREPARATION

Revision ID: 96050a4adeea
Revises: 0016945d3433
Create Date: 2025-09-13 21:19:29.860305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96050a4adeea'
down_revision: Union[str, None] = '0016945d3433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE pipelineitemtype ADD VALUE 'CHATBOT_PREPARATION'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###