"""Alter AttachmentModel add is_rag

Revision ID: 97d9a4204463
Revises: 348817890fe1
Create Date: 2025-09-05 20:20:20.894599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d9a4204463'
down_revision: Union[str, None] = '348817890fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('is_rag', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('fk_ragdoc_attachment'), 'rag_documents', type_='foreignkey')
    op.create_foreign_key(None, 'rag_documents', 'attachments', ['attachment_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rag_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ragdoc_attachment'), 'rag_documents', 'attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attachments', 'is_rag')
    # ### end Alembic commands ###