"""add reply_from_id to messages

Revision ID: 9ef60788418a
Revises: 55b7e5567ca7
Create Date: 2025-09-28 13:43:33.920777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef60788418a'
down_revision: Union[str, None] = '55b7e5567ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_from_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('reply_yes', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_yes')
    op.drop_column('messages', 'reply_from_id')
    # ### end Alembic commands ###