"""Alter Records add published column

Revision ID: a3911a75eb4b
Revises: 4617071d7bcd
Create Date: 2025-09-03 10:08:21.475937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3911a75eb4b'
down_revision: Union[str, None] = '4617071d7bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'published')
    # ### end Alembic commands ###