"""Alter RagChunks at index

Revision ID: a9e865df9205
Revises: 97d9a4204463
Create Date: 2025-09-06 09:35:46.175728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e865df9205'
down_revision: Union[str, None] = '97d9a4204463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_chunks', 'chunk_index')
    # ### end Alembic commands ###