"""Add owner_id to message

Revision ID: b24c55db76c1
Revises: 2b058f924cbf
Create Date: 2025-09-21 09:46:25.279002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24c55db76c1'
down_revision: Union[str, None] = '2b058f924cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('msg_content', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['owner_id'], ['id'])
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'owner_id')
    op.drop_column('messages', 'msg_content')
    # ### end Alembic commands ###