"""Alter Records add record_content

Revision ID: bbdf9afdd002
Revises: ec90614619aa
Create Date: 2025-09-03 14:17:59.174329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbdf9afdd002'
down_revision: Union[str, None] = 'ec90614619aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'record_content_type',
               existing_type=postgresql.ENUM('MEETING', 'LECTURE_CLASS', 'TUTORIAL_TRAINING', 'INTERVIEW', 'TALKSHOW', 'NEWS', 'DOCUMENTARY', 'ENTERTAINMENT', name='recordcontenttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'record_content_type',
               existing_type=postgresql.ENUM('MEETING', 'LECTURE_CLASS', 'TUTORIAL_TRAINING', 'INTERVIEW', 'TALKSHOW', 'NEWS', 'DOCUMENTARY', 'ENTERTAINMENT', name='recordcontenttype'),
               nullable=True)
    # ### end Alembic commands ###