"""Alter record add preparation-state1

Revision ID: bcbe3ab7d37a
Revises: f0d84b3e60ba
Create Date: 2025-09-13 21:49:32.775158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbe3ab7d37a'
down_revision: Union[str, None] = 'f0d84b3e60ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE recordchatbotpreparationstate ADD VALUE 'PREPARING'")
    op.execute("ALTER TYPE recordchatbotpreparationstate ADD VALUE 'DONE'")
    op.execute("ALTER TYPE recordchatbotpreparationstate ADD VALUE 'FAILED'")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###