"""Alter rag-doc-table FK attachment-id

Revision ID: c122b6983fc1
Revises: e1c82d5a7cdd
Create Date: 2025-09-13 14:04:17.777365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c122b6983fc1'
down_revision: Union[str, None] = 'e1c82d5a7cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_documents', 'attachment_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_documents', 'attachment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###