"""Add duration and remove start-end-time

Revision ID: c58dd66089f8
Revises: a5ecea984429
Create Date: 2025-09-12 13:40:22.946544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58dd66089f8'
down_revision: Union[str, None] = 'a5ecea984429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('duration', sa.Float(), nullable=True))
    op.drop_column('records', 'start_time')
    op.drop_column('records', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('records', 'duration')
    # ### end Alembic commands ###