"""add web_search

Revision ID: d455fc98bf63
Revises: 9ef60788418a
Create Date: 2025-09-28 13:45:59.216297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd455fc98bf63'
down_revision: Union[str, None] = '9ef60788418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('web_search', sa.Boolean(), nullable=True))
    op.drop_column('messages', 'reply_yes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_yes', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'web_search')
    # ### end Alembic commands ###