"""Alter pipeline-item-type CHATBOT_PREPARATION1

Revision ID: e484a064fda5
Revises: 96050a4adeea
Create Date: 2025-09-13 21:26:29.239198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e484a064fda5'
down_revision: Union[str, None] = '96050a4adeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    #op.execute("ALTER TYPE pipelineitemtype ADD VALUE 'CHATBOT_PREPARATION';")
    op.execute("""
            UPDATE record_pipeline_items
            SET "type" = 'CHATBOT_PREPARATION'::pipelineitemtype
            WHERE "type" = 'RAG_INDEX'::pipelineitemtype;
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###